version: '2'
services:
    worktimetracker-app:
        image: worktimetracker
        external_links:
            - worktimetracker-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/worktimetracker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    worktimetracker-mysql:
        extends:
            file: mysql.yml
            service: worktimetracker-mysql
